### ISSUE TITLE
資料格式相關問題

### ISSUE THREAD

**Issue by WenTingTseng** [allenyummy/EHR_NER#7]
您好:
謝謝回覆，根據您的readme.md上的說明，我有點不太懂label4qasl.txt 與 label4sl.txt 的格式
這個檔案目的是列出我資料中所有label的可能性嗎?例如:B-ADD、I-ADD、O...等等然後一種就列在一行嗎?

另外，simqasl_query.json和qasl_query.json兩個檔案是那個label對應到的中文嗎?比如說ADD對應到入院日期、DCD對應到出院日期
那如果Nested NER的話一個label會對應到多種可能性，假裝ADD會對應到入院日期也可能對應到住院日期，這樣該如何format資料

我嘗試弄一些跟你程式符合的假資料，希望能延續這項研究

謝謝，
Wen-Ting

**Comment by aics-ylchiang** [comment]
您好，

首先需事先定義您的資料集有哪些 entity type，接著，定義您欲採取的標記模式（BIO, BIOES, ….)，最後即可產出各種 label。

以此 repo 來舉例，
label type: B-ADD, I-ADD, B-DCD, I-DCD …O
entity type: ADD, DCD …

依序回答您的問題：

1. 對的，一個 label 列出一行，列出所有 label 的種類。

2. query.json 裡面放的是，針對不同的 entity type，您想對模型問什麼樣的問題。

3. 可以參考 README.md 提供的一筆資料。

謝謝

YL

**Comment by WenTingTseng** [comment]
OK，謝謝回覆。
我大致了解,我再實驗看看

謝謝，
Wen-Ting
